// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhblbrfxteluinpkkbiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoYmxicmZ4dGVsdWlucGtrYml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTMwMzMsImV4cCI6MjA3MTA4OTAzM30.hSk1eh9wYPpP0FO5Jtft-di_LVBRbhueVJky9Qg5FHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
